name: Create and Publish Workspace Images

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: "Image: gitpod-base"
        uses: docker/build-push-action@v2
        with:
          context: workspace-images/base
          push: true
          tags: openformation/gitpod-base:latest
      -
        name: "Image: gitpod-node"
        uses: docker/build-push-action@v2
        with:
          context: workspace-images/node
          push: true
          tags: openformation/gitpod-node:latest
      -
        name: "Image: gitpod-deno"
        uses: docker/build-push-action@v2
        with:
          context: workspace-images/deno
          push: true
          tags: openformation/gitpod-deno:latest
